### PR TITLE
[FIXED JENKINS-41744] ManagementLink to improve the supportability of the AD plugin

### PR DESCRIPTION
**Pull request by fbelzunc**
This PR intends to provide an easy way from the UI to:
* Check if the DNS resolution works
* Check if the domain exposes the GC
* Check if the domain exposes the LDAP catalog
* And for each domain controller provide: IP address/Login successful/Connection time/User lookup time

To implement this and to avoid the UI to get stuck testing login against DC I am using `jenkins.util.ProgressiveRendering`

* `ManagementLink` in Manage Jenkins
screen shot 2017-06-14 at 08 10 27

* `ManagementLink` view
screen shot 2017-06-14 at 08 10 17

https://issues.jenkins-ci.org/browse/JENKINS-41744

### CODE REVIEW

**Comment by daniel-beck** [comment]
Where's the administative monitor? Or do you mean management link?

**Comment by fbelzunc** [comment]
@daniel-beck You are right - sorry! 

My lack of experience!

**Comment by daniel-beck** [comment]
Adding a Windows icon (which I assume this is) may violate Microsoft trademark/copyright/logo usage policy. Did you check?

**Comment by fbelzunc** [comment]
@daniel-beck I took it from [this link](https://www.iconfinder.com/icons/1829987/brand_logo_network_social_windows_icon#size=128)
screen shot 2017-02-17 at 07 43 28

```
License: Creative Commons (Attribution 3.0 Unported) (help for licenses)
```

* Is this not enough?

**Comment by daniel-beck** [comment]
> License: Creative Commons (Attribution 3.0 Unported)

Where's the attribution?

**Comment by fbelzunc** [comment]
I think it will be easier if I create my own icon - I will delete this one and create my own icon.

**Pull request merged**
