### PR TITLE
[FIXED JENKINS-42831] Enable StartTls is always TRUE in the UI

### PR DESCRIPTION
**Pull request by escoem**
Please @reviewbybees @fbelzunc 

Just and easy change:

<f:checkbox checked="true" />

by 

<f:checkbox default="true" />

### CODE REVIEW

**Comment by fbelzunc** [comment]
🐝

**Comment by oleg-nenashev** [comment]
How is it going to be "always true"? If the field value is false, it is going to be false., no?

**Comment by fbelzunc** [comment]
@oleg-nenashev Yes, but on the UI it will always appears as true - although on disk it is fine.

pr71-example

**Comment by jglick** [comment]
But I would advise writing a test demonstrating the bug (using `JenkinsRule.configRoundtrip()`) and confirming the fix.

**Comment by fbelzunc** [comment]
@escoem Would you mind to write the test? I think it is easy.

**Pull request merged**
