### PR TITLE
[JENKINS-37582] Not return null inside the cache

### PR DESCRIPTION
**Pull request by fbelzunc**
https://issues.jenkins-ci.org/browse/JENKINS-37582

@reviewbybees CC @andresrc @jtnord

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Hmm... It may cause serious performance degradation.
I'm also not sure that usage of runtime <code> UserMayOrMayNotExistException</code> for groups (!) is a good idea. Maybe dependent logic does not handle it correctly

**Comment by fbelzunc** [comment]
> Hmm... It may cause serious performance degradation. 

I don't think that for the moment it will cause performance degradation in case it is not already causing them. 

But yes, it looks like I need to better follow:
http://stackoverflow.com/questions/8298285/handle-null-value-using-guava-mapmaker-cachebuilder

**Comment by oleg-nenashev** [comment]
Agreed. 🐝

**Comment by andresrc** [comment]
Exactly, when you need to cache an equivalent to `null` you should use something like `Optional`.

**Comment by fbelzunc** [comment]
@reviewbybees done

**Pull request merged**
